### ISSUE TITLE
(opinion) UDL usage should be simplified

### ISSUE THREAD

**Issue by seanmiddleditch** [codeinred/tuplet#1]
This is purely an opinion, so take with a grain of salt :)

I find the English-like numeral suffixes to be a little too "cute" and not necessarily helpful to code readability at scale. Especially when considering that, while software is often written in English, is is often written by non-native English speakers. Getting fancy with English numerals with UDL suffixes like `_nd` vs `_rd` seems like a recipe for confusion. It probably also increases the risk of unnecessary name clashes with other libraries when a particular function wants to `using namespace` UDLs from several different places.

I'd recommend dropping all the English-y UDLs and just sticking to `_tag`.

replace:

```c++
template <char... D> constexpr index_t<D...> operator""_tag() { return {}; }
template <char... D> constexpr index_t<D...> operator""_st() { return {}; }
template <char... D> constexpr index_t<D...> operator""_nd() { return {}; }
template <char... D> constexpr index_t<D...> operator""_rd() { return {}; }
template <char... D> constexpr index_t<D...> operator""_th() { return {}; }
```

with just:

```c++
template <char... D> constexpr index_t<D...> operator""_tag() { return {}; }
```

(Separately, I'm not sure the UDLs are all that helpful anyway; C++ made UDLs painful to use due to the need to always `using namespace blah::literals;` to access them; I'd generally just fallback to using `tag<N>` instead of `N_tag` anyway; it's one character longer, but cuts out an entire `using` statement.)

**Comment by codeinred** [comment]
Hi Sean,

I took this change into consideration, and I think you're right! I removed the other literals, so that only the `_tag` literal remains. I like having the literals because you'd either have to do `tag<0>()` or use `tag_v<0>`, both of which are uglier than just writing `0_tag`.

An example is seen here in this code in [index-test-2.cpp](test/index-test-2.cpp)
```cpp
bool is_good(int a, int b, std::string c) {
    return a == 1 && b == 2 && c == "Hello, world!";
}

int main() {
    using namespace tuplet::literals;
    auto tup = tuplet::tuple {1, 2, std::string("Hello, world!")};

    static_assert(
        std::is_same_v<std::tuple_element_t<0, decltype(tup)>, int>,
        "Expected int& at element 0");
    static_assert(
        std::is_same_v<std::tuple_element_t<1, decltype(tup)>, int>,
        "Expected int& at element 1");
    static_assert(
        std::is_same_v<std::tuple_element_t<2, decltype(tup)>, std::string>,
        "Expected std::string& at element 2");

    auto& a = tup[0_tag];
    auto& b = tup[1_tag];
    auto& c = tup[2_tag];
    return !is_good(a, b, c);
}
```
