### ISSUE TITLE
Please add the possibility to install the library

### ISSUE THREAD

**Issue by tetsuhaut** [codeinred/tuplet#2]
It would be great if your library provided some tuplet-config.cmake file so that users only have to call 
`find_package(tuplet <some version> REQUIRED)` in their CMakeLists.txt to be able to find your library, rather that  copying and pasting the 'tuplet/tuple.hpp' file.

Anyway, thank you for your work.

**Comment by bugwelle** [comment]
Should work now, see https://github.com/codeinred/tuplet/pull/6 :-)

**Comment by codeinred** [comment]
I've also added an #install section to the readme! https://github.com/codeinred/tuplet#installation

**Comment by bugwelle** [comment]
@codeinred That's great! And yet another thing I didn't know: `cmake --install build --prefix "/path/to/install"`. I didn't know that CMake 3.15 introduced that! So much better than `-DCMAKE_INSTALL_PREFIX`, etc. :smile:
