### ISSUE TITLE
Clang crashes with nested tuple 

### ISSUE THREAD

**Issue by c4v4** [codeinred/tuplet#26]
Hi, thank you for this tuple implementation, I was trying to implement something similar (with little success).

I might have stumbled into a problem with Clang (tried versions 13, 14, and 15). 
The issue arises when a tuple is nested into another tuple mixed with other types, like:

`tuplet::tuple<int, tuplet::tuple<int>> p;
`

Here is a godbolt link: https://godbolt.org/z/1e1hsWv84

Since clang crashes there should be a problem on its side (which I have no idea how to solve).
I was wondering if you know any workaround to make them work together.

Thanks!

**Comment by c4v4** [comment]
Opened a [new issue](https://github.com/llvm/llvm-project/issues/59566) in llvm project

**Comment by codeinred** [comment]
Hi Francesco! Thank you so much for identifying this issue. I'm sorry for the delayed response; I've been on winter holiday. This is really serious, and I'm glad that you caught it! I will review your PR

**Comment by codeinred** [comment]
I merged your fix, thank you so much!
